kind: Service
apiVersion: v1
metadata:
  name: firsthelidon
  labels:
    app: firsthelidon
spec:
  type: ClusterIP
  selector:
    app: firsthelidon
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: firsthelidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firsthelidon
  template:
    metadata:
      labels:
        app: firsthelidon
        version: v1
    spec:
      containers:
      - name: firsthelidon
        image: firsthelidon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
